apiVersion: v1
kind: Service
metadata: 
  name: pet-service
spec: 
 selector:
   app: pet-clinic
 type: LoadBalancer
 ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30601
